### PR TITLE
Visualization of the direction of the device

### PR DESCRIPTION
**Pull request by Alamoris**
In the current implementation, it is completely unclear where the "nose" of the device is directed.
In order not to overload the scene with elements, I propose adding a parameter that will tint the front and rear propellers in different colors, red and white, respectively. This logic used on DJI propellers on the f450 and f500 frame.

### CODE REVIEW

**Comment by vooon** [comment]
Could you please add screenshot from rviz to see the difference?

**Comment by Alamoris** [comment]
Here are a few screenshots with different numbers of device rotors. In some screenshots, added a direction arrow, for greater visibility
Screenshot from 2020-02-18 11-09-31
Screenshot from 2020-02-18 11-09-24
Screenshot from 2020-02-18 11-07-40
Screenshot from 2020-02-18 10-58-34
Screenshot from 2020-02-18 10-51-58
Screenshot from 2020-02-18 10-51-28

**Comment by okalachev** [comment]
@Alamoris, @vooon, I would prefer the rear propellers to be not so bright. Can we make the color adjustable?

`front_props` and `rear_props`, for example.

**Comment by vooon** [comment]
@okalachev , well, i think better to merge as is, and then you could add parameters.

**Pull request merged**
