### PR TITLE
mavros_msgs Ros2

### PR DESCRIPTION
**Pull request by mlautman**
This updates https://github.com/mavlink/mavros/pull/1007 to master and builds with ROS Crystal.

This PR will require https://github.com/ros-geographic-info/geographic_info/pull/26 to work

### CODE REVIEW

**Comment by amilcarlucas** [comment]
Is this still backwards compatible with ROS1 (Kinetic and melodic) ?
This needs a rebase

**Comment by amilcarlucas** [comment]
Is this still backwards compatible with ROS1 (Kinetic and melodic) ?
This needs a rebase

**Comment by TSC21** [comment]
> Is this still backwards compatible with ROS1 (Kinetic and melodic) ?
> This needs a rebase

No. This is left open as an example.

**Comment by mlautman** [comment]
Oh boy! Glad to see this get merged :)

**Pull request merged**
