### PR TITLE
Added Optitrack Motive full compatibility to mocap position

### PR DESCRIPTION
**Pull request by rosn**
Implemented Optitrack Motive coordinates uses (zxy)
   + Added /mavros/mocap/use_motive_zxy param (true use zxy ENU coordiates, false use xyz ENU coordinates)
   + Added auto transform from zxy to xyz (if use_motive_zxy set to true)

### CODE REVIEW

**Comment by vooon** [comment]
Not sure that i want this swap magick. May you write that as applying rotation?
Define rotation by `Eigen::AngleAxis` and then apply in to Quaternion and Point.

**Comment by rosn** [comment]
I understand that I'll see what I can do I'm not familiar with Eigen lib so might take me some time.

**Comment by tonybaltovski** [comment]
Just some thoughts.  Should this not be done prior to send the data to mavros?  It seems more reasonable to have the node interfacing with Motive to convert to the ROS standard.  The coordinate system recently changed in Motive 1.7.  In addition, shouldn't the pose be local for the mocap?

**Comment by rosn** [comment]
The data are sent using VRPN technology so the problem still be the same, if Optitrack could change that it would be cool but they won't. the think is would you like to have full compatibility with Mocap tech or not. If not I'll use my own branch but I think it should be usefull for mavros to have these functionnalities.

**Comment by rosn** [comment]
I got a message from optitrack, telling me the way to specify Z as the Up value for the ENU. Be careful this only apply the transformation to the data beeing sent. So you can close and reject this pull. Thank you for your attention.

**Pull request closed without merging**
