### PR TITLE
lib: update ArduPilot modes

### PR DESCRIPTION
**Pull request by rmackay9**
This updates some of the flight mode numbers to strings in line with recent releases.

### CODE REVIEW

**Comment by mhkabir** [comment]
@vooon Good to merge?

**Comment by rmackay9** [comment]
@vooon, I'm sure you're busy but if you could merge in this simple change that would be greatly appreciated.

**Comment by vooon** [comment]
@rmackay9 @mhkabir sorry, i'm missed that PR. Thank you!

**Comment by rmackay9** [comment]
@vooon, that's cool, thanks very much for pull it into master!

**Pull request merged**
