### PR TITLE
DO NOT MERGE: Perform the autopilot version request as broadcast

### PR DESCRIPTION
**Pull request by LorenzMeier**
@vooon What is the exact mechanism to send a broadcast command (with target_system && target_component == 0)? How can users configure the FCU ID and component ID in normal circumstances?

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Ok, found the params. So the only remaining question is about broadcast.
http://wiki.ros.org/mavros

**Comment by vooon** [comment]
Broadcast not possible now. We may add target to CommandLong.srv and CommandInt.srv, 
but that interfere with target parameters. So perhaps we should use int16 and use -1 as a default.
Or add broadcast flag (bool).

**Comment by vooon** [comment]
https://github.com/mavlink/mavros/commit/f2b3c6b48bebe176e76baa326b3bb9267ff38a8f - broadcast support.

**Comment by vooon** [comment]
@LorenzMeier i fixed your code, but seems there no FCU support.

Today stable:
```
[ WARN] [1436566864.879060737]: VER: request timeout, retries left 1
[ WARN] [1436566865.878676672]: VER: request timeout, retries left 0
[ WARN] [1436566866.878285620]: VER: your FCU don't support AUTOPILOT_VERSION, switched to default capabilities
```

And unicast:
```
[ INFO] [1436563540.116735751]: VER: Capabilities 0x00000000000004eb
[ INFO] [1436563540.116897939]: VER: Flight software:     00000000 (364d323ddf889734)
[ INFO] [1436563540.116984647]: VER: Middleware software: 00000000 (364d323ddf889734)
[ INFO] [1436563540.117088358]: VER: OS software:         00000000 (0000000000000000)
[ INFO] [1436563540.117168495]: VER: Board hardware:      00000000
[ INFO] [1436563540.117241180]: VER: VID/PID: 26ac:0011
[ INFO] [1436563540.117315624]: VER: UID: 3133470131383530
```

**Comment by LorenzMeier** [comment]
Are you sending the standard request command?
https://github.com/PX4/Firmware/blob/stable/src/modules/mavlink/mavlink_receiver.cpp#L286

**Comment by LorenzMeier** [comment]
No, the actual issue is here:
https://github.com/PX4/Firmware/blob/stable/src/modules/mavlink/mavlink_receiver.cpp#L275

Its not accepting the broadcast. I'll change that, sec.

**Comment by vooon** [comment]
Also i don't think that APM also handles broadcast. So need fallback to unicast.

**Comment by LorenzMeier** [comment]
BTW - have you seen this?
https://pixhawk.org/dev/simulation/native_sitl

**Comment by vooon** [comment]
There fallback:

```
[ WARN] [1436569934.589637411]: VER: broadcast request timeout, retries left 4
[ WARN] [1436569935.589986027]: VER: broadcast request timeout, retries left 3
[ WARN] [1436569936.589817818]: VER: unicast request timeout, retries left 2
[ INFO] [1436569936.593644918]: VER: 1.50: Capabilities 0x00000000000004eb
[ INFO] [1436569936.593810366]: VER: 1.50: Flight software:     00000000 (364d323ddf889734)
[ INFO] [1436569936.593953937]: VER: 1.50: Middleware software: 00000000 (364d323ddf889734)
[ INFO] [1436569936.594142794]: VER: 1.50: OS software:         00000000 (0000000000000000)
[ INFO] [1436569936.594288758]: VER: 1.50: Board hardware:      00000000
[ INFO] [1436569936.594439517]: VER: 1.50: VID/PID: 26ac:0011
[ INFO] [1436569936.594582947]: VER: 1.50: UID: 3133470131383530
```

So at least that don't break support for current firmwares.

**Comment by vooon** [comment]
Tested with APM SITL too.

```
[ INFO] [1436877686.944646570]: VER: 1.1: Capabilities 0x0000000000000000
[ INFO] [1436877686.944690983]: VER: 1.1: Flight software:     00000000 (6be0932d)
[ INFO] [1436877686.944734336]: VER: 1.1: Middleware software: 00000000 (        )
[ INFO] [1436877686.944771590]: VER: 1.1: OS software:         00000000 (        )
[ INFO] [1436877686.944820962]: VER: 1.1: Board hardware:      00000000
[ INFO] [1436877686.944868280]: VER: 1.1: VID/PID: 0000:0000
[ INFO] [1436877686.944909148]: VER: 1.1: UID: 0000000000000000
```

So good to merge.

**Pull request merged**
