### PR TITLE
Fix the setpoint_attitude

### PR DESCRIPTION
**Pull request by AlexisTM**
Fix the setpoint_attitude #793

### CODE REVIEW

**Comment by TSC21** [comment]
Saw now there is the .subscribe() method for message_fiters::Subscriber. But does this really solve the issue?

**Comment by TSC21** [comment]
@AndresR8 would you mind testing this and check if it solves your problem?

**Comment by TSC21** [comment]
@AlexisTM this patch does not solve the issue. After running the node and checking for the subscribers, it still seems there is no subscriber at all:
```
Subscriptions: 
 * /mavros/actuator_control [unknown type]
 * /mavros/hil/optical_flow [unknown type]
 * /mavros/global_position/set_gp_origin [unknown type]
 * /tf [tf2_msgs/TFMessage]
 * /mavros/setpoint_raw/attitude [unknown type]
 * /mavros/hil/state [unknown type]
 * /mavros/global_position/home [unknown type]
 * /mavros/setpoint_velocity/cmd_vel [unknown type]
 * /mavros/hil/gps [unknown type]
 * /mavros/setpoint_position/local [unknown type]
 * /mavros/odometry/odom [unknown type]
 * /mavros/mocap/pose [unknown type]
 * /mavros/hil/imu_ned [unknown type]
 * /mavros/hil/rc_inputs [unknown type]
 * /tf_static [unknown type]
 * /mavros/setpoint_raw/global [unknown type]
 * /mavros/vision_pose/pose_cov [unknown type]
 * /mavros/fake_gps/mocap/tf [unknown type]
 * /mavlink/to [unknown type]
 * /mavros/rc/override [unknown type]
 * /mavros/setpoint_raw/local [unknown type]
 * /mavros/setpoint_velocity/cmd_vel_unstamped [unknown type]
 * /mavros/vision_pose/pose [unknown type]
 * /mavros/setpoint_accel/accel [unknown type]
 * /clock [rosgraph_msgs/Clock]
 * /mavros/vision_speed/speed_vector [unknown type]
 * /mavros/adsb/send [unknown type]
 * /mavros/home_position/set [unknown type]
```
I believe the problem though could be when creating the `message_filters::Synchronizer`. We probably need to put is as private and then init is on the `initialize()` method.

**Comment by AlexisTM** [comment]
Can you double check you sourced the workspace right before starting Mavros?

# Without patch

```bash
$ roslaunch mavros px4.launch fcu_url:="udp://:14540@127.0.0.1:14557" 
$ rostopic list
/diagnostics
/mavlink/from
/mavlink/to
/mavros/actuator_control
/mavros/adsb/send
/mavros/adsb/vehicle
/mavros/altitude
/mavros/battery
/mavros/cam_imu_sync/cam_imu_stamp
/mavros/extended_state
/mavros/fake_gps/mocap/tf
/mavros/global_position/compass_hdg
/mavros/global_position/global
/mavros/global_position/gp_lp_offset
/mavros/global_position/gp_origin
/mavros/global_position/home
/mavros/global_position/local
/mavros/global_position/raw/fix
/mavros/global_position/raw/gps_vel
/mavros/global_position/rel_alt
/mavros/global_position/set_gp_origin
/mavros/hil/actuator_controls
/mavros/hil/controls
/mavros/hil/gps
/mavros/hil/imu_ned
/mavros/hil/optical_flow
/mavros/hil/rc_inputs
/mavros/hil/state
/mavros/home_position/home
/mavros/home_position/set
/mavros/imu/atm_pressure
/mavros/imu/data
/mavros/imu/data_raw
/mavros/imu/mag
/mavros/imu/temperature
/mavros/local_position/odom
/mavros/local_position/pose
/mavros/local_position/velocity
/mavros/manual_control/control
/mavros/mission/waypoints
/mavros/mocap/pose
/mavros/odometry/odom
/mavros/px4flow/ground_distance
/mavros/px4flow/raw/optical_flow_rad
/mavros/px4flow/temperature
/mavros/radio_status
/mavros/rc/in
/mavros/rc/out
/mavros/rc/override
/mavros/setpoint_accel/accel
/mavros/setpoint_position/local
/mavros/setpoint_raw/attitude
/mavros/setpoint_raw/global
/mavros/setpoint_raw/local
/mavros/setpoint_raw/target_attitude
/mavros/setpoint_raw/target_global
/mavros/setpoint_raw/target_local
/mavros/setpoint_velocity/cmd_vel
/mavros/setpoint_velocity/cmd_vel_unstamped
/mavros/state
/mavros/target_actuator_control
/mavros/time_reference
/mavros/vfr_hud
/mavros/vision_pose/pose
/mavros/vision_pose/pose_cov
/mavros/vision_speed/speed_vector
/mavros/wind_estimation
/rosout
/rosout_agg
/tf
/tf_static
```

With the Patch

```bash
$ source ~/ws/mavros/setup.bash
$ roslaunch mavros px4.launch fcu_url:="udp://:14540@127.0.0.1:14557" 
$ rostopic list
/diagnostics
/mavlink/from
/mavlink/to
/mavros/actuator_control
/mavros/adsb/send
/mavros/adsb/vehicle
/mavros/altitude
/mavros/battery
/mavros/cam_imu_sync/cam_imu_stamp
/mavros/extended_state
/mavros/fake_gps/mocap/tf
/mavros/global_position/compass_hdg
/mavros/global_position/global
/mavros/global_position/gp_lp_offset
/mavros/global_position/gp_origin
/mavros/global_position/home
/mavros/global_position/local
/mavros/global_position/raw/fix
/mavros/global_position/raw/gps_vel
/mavros/global_position/rel_alt
/mavros/global_position/set_gp_origin
/mavros/hil/actuator_controls
/mavros/hil/controls
/mavros/hil/gps
/mavros/hil/imu_ned
/mavros/hil/optical_flow
/mavros/hil/rc_inputs
/mavros/hil/state
/mavros/home_position/home
/mavros/home_position/set
/mavros/imu/atm_pressure
/mavros/imu/data
/mavros/imu/data_raw
/mavros/imu/mag
/mavros/imu/temperature
/mavros/local_position/odom
/mavros/local_position/pose
/mavros/local_position/velocity
/mavros/manual_control/control
/mavros/mission/waypoints
/mavros/mocap/pose
/mavros/odometry/odom
/mavros/px4flow/ground_distance
/mavros/px4flow/raw/optical_flow_rad
/mavros/px4flow/temperature
/mavros/radio_status
/mavros/rc/in
/mavros/rc/out
/mavros/rc/override
/mavros/setpoint_accel/accel
/mavros/setpoint_attitude/cmd_vel
/mavros/setpoint_attitude/thrust
/mavros/setpoint_position/local
/mavros/setpoint_raw/attitude
/mavros/setpoint_raw/global
/mavros/setpoint_raw/local
/mavros/setpoint_raw/target_attitude
/mavros/setpoint_raw/target_global
/mavros/setpoint_raw/target_local
/mavros/setpoint_velocity/cmd_vel
/mavros/setpoint_velocity/cmd_vel_unstamped
/mavros/state
/mavros/target_actuator_control
/mavros/time_reference
/mavros/vfr_hud
/mavros/vision_pose/pose
/mavros/vision_pose/pose_cov
/mavros/vision_speed/speed_vector
/mavros/wind_estimation
/rosout
/rosout_agg
/tf
/tf_static
```

**Comment by TSC21** [comment]
weird. somehow in my workspace I'm not able to get any subscriber still.

**Comment by vooon** [comment]
I tested. Now i see (depending on use_quaternion) thrust, cmd_vel or target_attitude.

@AlexisTM thank you.

**Comment by vooon** [comment]
Full dump:
```
root@06dc880427d0:/# rosnode info /mavros
--------------------------------------------------------------------------------
Node [/mavros]
Publications: 
 * /mavros/manual_control/control [mavros_msgs/ManualControl]
 * /mavros/adsb/vehicle [mavros_msgs/ADSBVehicle]
 * /tf [tf2_msgs/TFMessage]
 * /mavros/radio_status [mavros_msgs/RadioStatus]
 * /mavros/setpoint_raw/target_local [mavros_msgs/PositionTarget]
 * /mavros/imu/atm_pressure [sensor_msgs/FluidPressure]
 * /mavros/altitude [mavros_msgs/Altitude]
 * /mavros/global_position/compass_hdg [std_msgs/Float64]
 * /mavros/hil/actuator_controls [mavros_msgs/HilActuatorControls]
 * /mavros/global_position/global [sensor_msgs/NavSatFix]
 * /mavros/target_actuator_control [mavros_msgs/ActuatorControl]
 * /mavlink/from [mavros_msgs/Mavlink]
 * /mavros/local_position/pose [geometry_msgs/PoseStamped]
 * /mavros/imu/data [sensor_msgs/Imu]
 * /mavros/wind_estimation [geometry_msgs/TwistStamped]
 * /mavros/setpoint_raw/target_global [mavros_msgs/GlobalPositionTarget]
 * /mavros/global_position/gp_origin [geographic_msgs/GeoPointStamped]
 * /mavros/imu/temperature [sensor_msgs/Temperature]
 * /mavros/px4flow/raw/optical_flow_rad [mavros_msgs/OpticalFlowRad]
 * /diagnostics [diagnostic_msgs/DiagnosticArray]
 * /mavros/global_position/raw/fix [sensor_msgs/NavSatFix]
 * /mavros/battery [sensor_msgs/BatteryState]
 * /mavros/setpoint_raw/target_attitude [mavros_msgs/AttitudeTarget]
 * /mavros/imu/data_raw [sensor_msgs/Imu]
 * /mavros/mission/waypoints [mavros_msgs/WaypointList]
 * /mavros/cam_imu_sync/cam_imu_stamp [mavros_msgs/CamIMUStamp]
 * /mavros/state [mavros_msgs/State]
 * /mavros/rc/in [mavros_msgs/RCIn]
 * /rosout [rosgraph_msgs/Log]
 * /mavros/global_position/local [nav_msgs/Odometry]
 * /mavros/vfr_hud [mavros_msgs/VFR_HUD]
 * /mavros/px4flow/ground_distance [sensor_msgs/Range]
 * /mavros/px4flow/temperature [sensor_msgs/Temperature]
 * /mavros/global_position/rel_alt [std_msgs/Float64]
 * /mavros/imu/mag [sensor_msgs/MagneticField]
 * /mavros/local_position/odom [nav_msgs/Odometry]
 * /mavros/extended_state [mavros_msgs/ExtendedState]
 * /mavros/hil/controls [mavros_msgs/HilControls]
 * /mavros/local_position/velocity [geometry_msgs/TwistStamped]
 * /mavros/global_position/gp_lp_offset [geometry_msgs/PoseStamped]
 * /mavros/global_position/raw/gps_vel [geometry_msgs/TwistStamped]
 * /mavros/rc/out [mavros_msgs/RCOut]
 * /mavros/home_position/home [mavros_msgs/HomePosition]
 * /mavros/time_reference [sensor_msgs/TimeReference]

Subscriptions: 
 * /mavros/actuator_control [unknown type]
 * /mavros/hil/optical_flow [unknown type]
 * /mavros/global_position/set_gp_origin [unknown type]
 * /mavros/setpoint_attitude/cmd_vel [unknown type]
 * /tf [tf2_msgs/TFMessage]
 * /mavros/setpoint_raw/attitude [unknown type]
 * /mavros/hil/state [unknown type]
 * /mavros/global_position/home [unknown type]
 * /mavros/setpoint_velocity/cmd_vel [unknown type]
 * /mavros/hil/gps [unknown type]
 * /mavros/setpoint_position/local [unknown type]
 * /mavros/odometry/odom [unknown type]
 * /mavros/mocap/pose [unknown type]
 * /mavros/hil/imu_ned [unknown type]
 * /mavros/hil/rc_inputs [unknown type]
 * /tf_static [unknown type]
 * /mavros/setpoint_raw/global [unknown type]
 * /mavros/vision_pose/pose_cov [unknown type]
 * /mavros/fake_gps/mocap/tf [unknown type]
 * /mavlink/to [unknown type]
 * /mavros/rc/override [unknown type]
 * /mavros/setpoint_raw/local [unknown type]
 * /mavros/setpoint_velocity/cmd_vel_unstamped [unknown type]
 * /mavros/vision_pose/pose [unknown type]
 * /mavros/setpoint_attitude/thrust [unknown type]
 * /mavros/setpoint_accel/accel [unknown type]
 * /mavros/vision_speed/speed_vector [unknown type]
 * /mavros/adsb/send [unknown type]
 * /mavros/home_position/set [unknown type]

Services: 
 * /mavros/cmd/set_home
 * /mavros/param/get
 * /mavros/ftp/checksum
 * /mavros/cmd/land
 * /mavros/ftp/mkdir
 * /mavros/param/pull
 * /mavros/mission/push
 * /mavros/ftp/close
 * /mavros/ftp/rmdir
 * /mavros/ftp/list
 * /mavros/cmd/command_int
 * /mavros/param/push
 * /mavros/param/set
 * /mavros/cmd/takeoff
 * /mavros/ftp/truncate
 * /mavros/get_loggers
 * /mavros/home_position/req_update
 * /mavros/cmd/command
 * /mavros/ftp/open
 * /mavros/ftp/rename
 * /mavros/ftp/read
 * /mavros/ftp/remove
 * /mavros/ftp/reset
 * /mavros/mission/pull
 * /mavros/mission/clear
 * /mavros/set_stream_rate
 * /mavros/set_mode
 * /mavros/cmd/arming
 * /mavros/cmd/trigger_control
 * /mavros/set_logger_level
 * /mavros/mission/set_current
 * /mavros/ftp/write


contacting node http://06dc880427d0:36233/ ...
Pid: 26145
Connections:
 * topic: /rosout
    * to: /rosout
    * direction: outbound
    * transport: TCPROS
 * topic: /tf
    * to: /mavros
    * direction: outbound
    * transport: INTRAPROCESS
 * topic: /tf
    * to: /mavros (http://06dc880427d0:36233/)
    * direction: inbound
    * transport: INTRAPROCESS

root@06dc880427d0:/# rosnode info /mavros
--------------------------------------------------------------------------------
Node [/mavros]
Publications: 
 * /mavros/manual_control/control [mavros_msgs/ManualControl]
 * /mavros/adsb/vehicle [mavros_msgs/ADSBVehicle]
 * /tf [tf2_msgs/TFMessage]
 * /mavros/radio_status [mavros_msgs/RadioStatus]
 * /mavros/setpoint_raw/target_local [mavros_msgs/PositionTarget]
 * /mavros/imu/atm_pressure [sensor_msgs/FluidPressure]
 * /mavros/altitude [mavros_msgs/Altitude]
 * /mavros/global_position/compass_hdg [std_msgs/Float64]
 * /mavros/hil/actuator_controls [mavros_msgs/HilActuatorControls]
 * /mavros/global_position/global [sensor_msgs/NavSatFix]
 * /mavros/target_actuator_control [mavros_msgs/ActuatorControl]
 * /mavlink/from [mavros_msgs/Mavlink]
 * /mavros/local_position/pose [geometry_msgs/PoseStamped]
 * /mavros/imu/data [sensor_msgs/Imu]
 * /mavros/wind_estimation [geometry_msgs/TwistStamped]
 * /mavros/setpoint_raw/target_global [mavros_msgs/GlobalPositionTarget]
 * /mavros/global_position/gp_origin [geographic_msgs/GeoPointStamped]
 * /mavros/imu/temperature [sensor_msgs/Temperature]
 * /mavros/px4flow/raw/optical_flow_rad [mavros_msgs/OpticalFlowRad]
 * /diagnostics [diagnostic_msgs/DiagnosticArray]
 * /mavros/global_position/raw/fix [sensor_msgs/NavSatFix]
 * /mavros/battery [sensor_msgs/BatteryState]
 * /mavros/setpoint_raw/target_attitude [mavros_msgs/AttitudeTarget]
 * /mavros/imu/data_raw [sensor_msgs/Imu]
 * /mavros/mission/waypoints [mavros_msgs/WaypointList]
 * /mavros/cam_imu_sync/cam_imu_stamp [mavros_msgs/CamIMUStamp]
 * /mavros/state [mavros_msgs/State]
 * /mavros/rc/in [mavros_msgs/RCIn]
 * /rosout [rosgraph_msgs/Log]
 * /mavros/global_position/local [nav_msgs/Odometry]
 * /mavros/vfr_hud [mavros_msgs/VFR_HUD]
 * /mavros/px4flow/ground_distance [sensor_msgs/Range]
 * /mavros/px4flow/temperature [sensor_msgs/Temperature]
 * /mavros/global_position/rel_alt [std_msgs/Float64]
 * /mavros/imu/mag [sensor_msgs/MagneticField]
 * /mavros/local_position/odom [nav_msgs/Odometry]
 * /mavros/extended_state [mavros_msgs/ExtendedState]
 * /mavros/hil/controls [mavros_msgs/HilControls]
 * /mavros/local_position/velocity [geometry_msgs/TwistStamped]
 * /mavros/global_position/gp_lp_offset [geometry_msgs/PoseStamped]
 * /mavros/global_position/raw/gps_vel [geometry_msgs/TwistStamped]
 * /mavros/rc/out [mavros_msgs/RCOut]
 * /mavros/home_position/home [mavros_msgs/HomePosition]
 * /mavros/time_reference [sensor_msgs/TimeReference]

Subscriptions: 
 * /mavros/actuator_control [unknown type]
 * /mavros/hil/optical_flow [unknown type]
 * /mavros/global_position/set_gp_origin [unknown type]
 * /tf [tf2_msgs/TFMessage]
 * /mavros/setpoint_raw/attitude [unknown type]
 * /mavros/hil/state [unknown type]
 * /mavros/global_position/home [unknown type]
 * /mavros/setpoint_velocity/cmd_vel [unknown type]
 * /mavros/hil/gps [unknown type]
 * /mavros/setpoint_position/local [unknown type]
 * /mavros/odometry/odom [unknown type]
 * /mavros/mocap/pose [unknown type]
 * /mavros/hil/imu_ned [unknown type]
 * /mavros/hil/rc_inputs [unknown type]
 * /tf_static [unknown type]
 * /mavros/setpoint_raw/global [unknown type]
 * /mavros/vision_pose/pose_cov [unknown type]
 * /mavros/fake_gps/mocap/tf [unknown type]
 * /mavlink/to [unknown type]
 * /mavros/rc/override [unknown type]
 * /mavros/setpoint_attitude/target_attitude [unknown type]
 * /mavros/setpoint_raw/local [unknown type]
 * /mavros/setpoint_velocity/cmd_vel_unstamped [unknown type]
 * /mavros/vision_pose/pose [unknown type]
 * /mavros/setpoint_attitude/thrust [unknown type]
 * /mavros/setpoint_accel/accel [unknown type]
 * /mavros/vision_speed/speed_vector [unknown type]
 * /mavros/adsb/send [unknown type]
 * /mavros/home_position/set [unknown type]

Services: 
 * /mavros/cmd/set_home
 * /mavros/param/get
 * /mavros/ftp/checksum
 * /mavros/cmd/land
 * /mavros/ftp/mkdir
 * /mavros/param/pull
 * /mavros/mission/push
 * /mavros/ftp/close
 * /mavros/ftp/rmdir
 * /mavros/ftp/list
 * /mavros/cmd/command_int
 * /mavros/param/push
 * /mavros/param/set
 * /mavros/cmd/takeoff
 * /mavros/ftp/truncate
 * /mavros/get_loggers
 * /mavros/home_position/req_update
 * /mavros/cmd/command
 * /mavros/ftp/open
 * /mavros/ftp/rename
 * /mavros/ftp/read
 * /mavros/ftp/remove
 * /mavros/ftp/reset
 * /mavros/mission/pull
 * /mavros/mission/clear
 * /mavros/set_stream_rate
 * /mavros/set_mode
 * /mavros/cmd/arming
 * /mavros/cmd/trigger_control
 * /mavros/set_logger_level
 * /mavros/mission/set_current
 * /mavros/ftp/write


contacting node http://06dc880427d0:46381/ ...
Pid: 29125
Connections:
 * topic: /rosout
    * to: /rosout
    * direction: outbound
    * transport: TCPROS
 * topic: /tf
    * to: /mavros
    * direction: outbound
    * transport: INTRAPROCESS
 * topic: /tf
    * to: /mavros (http://06dc880427d0:46381/)
    * direction: inbound
    * transport: INTRAPROCESS
```

**Comment by TSC21** [comment]
ok if it works good. I'm having issues with my workspaces

**Comment by TSC21** [comment]
Yeah confirmed now. Looks like I missed http://docs.ros.org/kinetic/api/message_filters/html/c++/classmessage__filters_1_1Subscriber.html#a421e36187039ed51ac032f1ee63695e0. Thanks @AlexisTM

**Comment by AlexisTM** [comment]
You are welcome!

**Pull request merged**
