### PR TITLE
Diagnose up-to 10 batteries

### PR DESCRIPTION
**Pull request by amilcarlucas**
I am open to suggestions to avoid the third commit

### CODE REVIEW

**Comment by amilcarlucas** [comment]
Tested to work in hardware, but I do not like the third commit, for obvious reasons.

**Comment by amilcarlucas** [comment]
@vooon can you help me out here?

**Comment by vooon** [comment]
I think emplace should construct object, so you should only provide constructor arguments. Also for single-arg it's recommended to use `explicit` keyword.
Mutex makes class non-copyable, so that's the reason, but what if we use move-semantics?

Also can we use `std::unordered_map<id, diag>` instead of vector, so we won't be limited by 10 bats.

**Comment by amilcarlucas** [comment]
Thanks, but the error is still there:
```
/usr/include/c++/7/ext/new_allocator.h: In instantiation of ‘void __gnu_cxx::new_allocator<_Tp>::construct(_Up*, _Args&& ...) [with _Up = mavros::std_plugins::BatteryStatusDiag; _Args = {mavros::std_plugins::BatteryStatusDiag}; _Tp = mavros::std_plugins::BatteryStatusDiag]’:
/usr/include/c++/7/bits/alloc_traits.h:475:4:   required from ‘static void std::allocator_traits<std::allocator<_CharT> >::construct(std::allocator_traits<std::allocator<_CharT> >::allocator_type&, _Up*, _Args&& ...) [with _Up = mavros::std_plugins::BatteryStatusDiag; _Args = {mavros::std_plugins::BatteryStatusDiag}; _Tp = mavros::std_plugins::BatteryStatusDiag; std::allocator_traits<std::allocator<_CharT> >::allocator_type = std::allocator<mavros::std_plugins::BatteryStatusDiag>]’
/usr/include/c++/7/bits/vector.tcc:100:30:   required from ‘void std::vector<_Tp, _Alloc>::emplace_back(_Args&& ...) [with _Args = {mavros::std_plugins::BatteryStatusDiag}; _Tp = mavros::std_plugins::BatteryStatusDiag; _Alloc = std::allocator<mavros::std_plugins::BatteryStatusDiag>]’
/media/amilcar/DATA/projekte/Multicopter/vw_westrampe/companion/ros_ws/src/mavros/mavros/src/plugins/sys_status.cpp:455:65:   required from here
/usr/include/c++/7/ext/new_allocator.h:136:4: error: use of deleted function ‘mavros::std_plugins::BatteryStatusDiag::BatteryStatusDiag(mavros::std_plugins::BatteryStatusDiag&&)’
  { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/media/amilcar/DATA/projekte/Multicopter/vw_westrampe/companion/ros_ws/src/mavros/mavros/src/plugins/sys_status.cpp:286:7: note: ‘mavros::std_plugins::BatteryStatusDiag::BatteryStatusDiag(mavros::std_plugins::BatteryStatusDiag&&)’ is implicitly deleted because the default definition would be ill-formed:
 class BatteryStatusDiag : public diagnostic_updater::DiagnosticTask
       ^~~~~~~~~~~~~~~~~
/media/amilcar/DATA/projekte/Multicopter/vw_westrampe/companion/ros_ws/src/mavros/mavros/src/plugins/sys_status.cpp:286:7: error: use of deleted function ‘std::mutex::mutex(const std::mutex&)’
In file included from /usr/include/c++/7/mutex:43:0,
                 from /media/amilcar/DATA/projekte/Multicopter/vw_westrampe/companion/ros_ws/src/mavros/libmavconn/include/mavconn/interface.h:27,
                 from /media/amilcar/DATA/projekte/Multicopter/vw_westrampe/companion/ros_ws/src/mavros/mavros/include/mavros/mavros_plugin.h:24,
                 from /media/amilcar/DATA/projekte/Multicopter/vw_westrampe/companion/ros_ws/src/mavros/mavros/src/plugins/sys_status.cpp:17:
/usr/include/c++/7/bits/std_mutex.h:97:5: note: declared here
     mutex(const mutex&) = delete;
     ^~~~~
In file included from /usr/include/c++/7/vector:62:0,
                 from /media/amilcar/DATA/projekte/Multicopter/vw_westrampe/companion/ros_ws/src/mavros/mavros/include/mavros/mavros_plugin.h:21,
                 from /media/amilcar/DATA/projekte/Multicopter/vw_westrampe/companion/ros_ws/src/mavros/mavros/src/plugins/sys_status.cpp:17:
/usr/include/c++/7/bits/stl_construct.h: In instantiation of ‘void std::_Construct(_T1*, _Args&& ...) [with _T1 = mavros::std_plugins::BatteryStatusDiag; _Args = {mavros::std_plugins::BatteryStatusDiag}]’:
/usr/include/c++/7/bits/stl_uninitialized.h:83:18:   required from ‘static _ForwardIterator std::__uninitialized_copy<_TrivialValueTypes>::__uninit_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = std::move_iterator<mavros::std_plugins::BatteryStatusDiag*>; _ForwardIterator = mavros::std_plugins::BatteryStatusDiag*; bool _TrivialValueTypes = false]’
/usr/include/c++/7/bits/stl_uninitialized.h:134:15:   required from ‘_ForwardIterator std::uninitialized_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = std::move_iterator<mavros::std_plugins::BatteryStatusDiag*>; _ForwardIterator = mavros::std_plugins::BatteryStatusDiag*]’
/usr/include/c++/7/bits/stl_uninitialized.h:289:37:   required from ‘_ForwardIterator std::__uninitialized_copy_a(_InputIterator, _InputIterator, _ForwardIterator, std::allocator<_Tp>&) [with _InputIterator = std::move_iterator<mavros::std_plugins::BatteryStatusDiag*>; _ForwardIterator = mavros::std_plugins::BatteryStatusDiag*; _Tp = mavros::std_plugins::BatteryStatusDiag]’
/usr/include/c++/7/bits/stl_vector.h:1263:35:   required from ‘std::vector<_Tp, _Alloc>::pointer std::vector<_Tp, _Alloc>::_M_allocate_and_copy(std::vector<_Tp, _Alloc>::size_type, _ForwardIterator, _ForwardIterator) [with _ForwardIterator = std::move_iterator<mavros::std_plugins::BatteryStatusDiag*>; _Tp = mavros::std_plugins::BatteryStatusDiag; _Alloc = std::allocator<mavros::std_plugins::BatteryStatusDiag>; std::vector<_Tp, _Alloc>::pointer = mavros::std_plugins::BatteryStatusDiag*; std::vector<_Tp, _Alloc>::size_type = long unsigned int]’
/usr/include/c++/7/bits/vector.tcc:73:40:   required from ‘void std::vector<_Tp, _Alloc>::reserve(std::vector<_Tp, _Alloc>::size_type) [with _Tp = mavros::std_plugins::BatteryStatusDiag; _Alloc = std::allocator<mavros::std_plugins::BatteryStatusDiag>; std::vector<_Tp, _Alloc>::size_type = long unsigned int]’
/media/amilcar/DATA/projekte/Multicopter/vw_westrampe/companion/ros_ws/src/mavros/mavros/src/plugins/sys_status.cpp:454:42:   required from here
/usr/include/c++/7/bits/stl_construct.h:75:7: error: use of deleted function ‘mavros::std_plugins::BatteryStatusDiag::BatteryStatusDiag(mavros::std_plugins::BatteryStatusDiag&&)’
     { ::new(static_cast<void*>(__p)) _T1(std::forward<_Args>(__args)...); }
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/7/functional:58:0,
                 from /media/amilcar/DATA/projekte/Multicopter/vw_westrampe/companion/ros_ws/src/mavros/mavros/include/mavros/mavros_plugin.h:22,
                 from /media/amilcar/DATA/projekte/Multicopter/vw_westrampe/companion/ros_ws/src/mavros/mavros/src/plugins/sys_status.cpp:17:
/usr/include/c++/7/bits/std_function.h:685:7: error: ‘std::function<_Res(_ArgTypes ...)>::function(_Functor) [with _Functor = mavros::plugin::PluginBase::make_handler(void (_C::*)(const mavlink_message_t*, _T&)) [with _C = mavros::std_plugins::SystemStatusPlugin; _T = mavlink::minimal::msg::HEARTBEAT; mavros::plugin::PluginBase::HandlerInfo = std::tuple<unsigned int, const char*, long unsigned int, std::function<void(const mavlink::__mavlink_message*, mavconn::Framing)> >; mavlink::mavlink_message_t = mavlink::__mavlink_message]::<lambda(const mavlink_message_t*, mavconn::Framing)>; <template-parameter-2-2> = void; <template-parameter-2-3> = void; _Res = void; _ArgTypes = {const mavlink::__mavlink_message*, mavconn::Framing}]’, declared using local type ‘mavros::plugin::PluginBase::make_handler(void (_C::*)(const mavlink_message_t*, _T&)) [with _C = mavros::std_plugins::SystemStatusPlugin; _T = mavlink::minimal::msg::HEARTBEAT; mavros::plugin::PluginBase::HandlerInfo = std::tuple<unsigned int, const char*, long unsigned int, std::function<void(const mavlink::__mavlink_message*, mavconn::Framing)> >; mavlink::mavlink_message_t = mavlink::__mavlink_message]::<lambda(const mavlink_message_t*, mavconn::Framing)>’, is used but never defined [-fpermissive]
       function<_Res(_ArgTypes...)>::
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/7/bits/std_function.h:685:7: error: ‘std::function<_Res(_ArgTypes ...)>::function(_Functor) [with _Functor = mavros::plugin::PluginBase::make_handler(void (_C::*)(const mavlink_message_t*, _T&)) [with _C = mavros::std_plugins::SystemStatusPlugin; _T = mavlink::common::msg::SYS_STATUS; mavros::plugin::PluginBase::HandlerInfo = std::tuple<unsigned int, const char*, long unsigned int, std::function<void(const mavlink::__mavlink_message*, mavconn::Framing)> >; mavlink::mavlink_message_t = mavlink::__mavlink_message]::<lambda(const mavlink_message_t*, mavconn::Framing)>; <template-parameter-2-2> = void; <template-parameter-2-3> = void; _Res = void; _ArgTypes = {const mavlink::__mavlink_message*, mavconn::Framing}]’, declared using local type ‘mavros::plugin::PluginBase::make_handler(void (_C::*)(const mavlink_message_t*, _T&)) [with _C = mavros::std_plugins::SystemStatusPlugin; _T = mavlink::common::msg::SYS_STATUS; mavros::plugin::PluginBase::HandlerInfo = std::tuple<unsigned int, const char*, long unsigned int, std::function<void(const mavlink::__mavlink_message*, mavconn::Framing)> >; mavlink::mavlink_message_t = mavlink::__mavlink_message]::<lambda(const mavlink_message_t*, mavconn::Framing)>’, is used but never defined [-fpermissive]
/usr/include/c++/7/bits/std_function.h:685:7: error: ‘std::function<_Res(_ArgTypes ...)>::function(_Functor) [with _Functor = mavros::plugin::PluginBase::make_handler(void (_C::*)(const mavlink_message_t*, _T&)) [with _C = mavros::std_plugins::SystemStatusPlugin; _T = mavlink::common::msg::STATUSTEXT; mavros::plugin::PluginBase::HandlerInfo = std::tuple<unsigned int, const char*, long unsigned int, std::function<void(const mavlink::__mavlink_message*, mavconn::Framing)> >; mavlink::mavlink_message_t = mavlink::__mavlink_message]::<lambda(const mavlink_message_t*, mavconn::Framing)>; <template-parameter-2-2> = void; <template-parameter-2-3> = void; _Res = void; _ArgTypes = {const mavlink::__mavlink_message*, mavconn::Framing}]’, declared using local type ‘mavros::plugin::PluginBase::make_handler(void (_C::*)(const mavlink_message_t*, _T&)) [with _C = mavros::std_plugins::SystemStatusPlugin; _T = mavlink::common::msg::STATUSTEXT; mavros::plugin::PluginBase::HandlerInfo = std::tuple<unsigned int, const char*, long unsigned int, std::function<void(const mavlink::__mavlink_message*, mavconn::Framing)> >; mavlink::mavlink_message_t = mavlink::__mavlink_message]::<lambda(const mavlink_message_t*, mavconn::Framing)>’, is used but never defined [-fpermissive]
/usr/include/c++/7/bits/std_function.h:685:7: error: ‘std::function<_Res(_ArgTypes ...)>::function(_Functor) [with _Functor = mavros::plugin::PluginBase::make_handler(void (_C::*)(const mavlink_message_t*, _T&)) [with _C = mavros::std_plugins::SystemStatusPlugin; _T = mavlink::ardupilotmega::msg::MEMINFO; mavros::plugin::PluginBase::HandlerInfo = std::tuple<unsigned int, const char*, long unsigned int, std::function<void(const mavlink::__mavlink_message*, mavconn::Framing)> >; mavlink::mavlink_message_t = mavlink::__mavlink_message]::<lambda(const mavlink_message_t*, mavconn::Framing)>; <template-parameter-2-2> = void; <template-parameter-2-3> = void; _Res = void; _ArgTypes = {const mavlink::__mavlink_message*, mavconn::Framing}]’, declared using local type ‘mavros::plugin::PluginBase::make_handler(void (_C::*)(const mavlink_message_t*, _T&)) [with _C = mavros::std_plugins::SystemStatusPlugin; _T = mavlink::ardupilotmega::msg::MEMINFO; mavros::plugin::PluginBase::HandlerInfo = std::tuple<unsigned int, const char*, long unsigned int, std::function<void(const mavlink::__mavlink_message*, mavconn::Framing)> >; mavlink::mavlink_message_t = mavlink::__mavlink_message]::<lambda(const mavlink_message_t*, mavconn::Framing)>’, is used but never defined [-fpermissive]
/usr/include/c++/7/bits/std_function.h:685:7: error: ‘std::function<_Res(_ArgTypes ...)>::function(_Functor) [with _Functor = mavros::plugin::PluginBase::make_handler(void (_C::*)(const mavlink_message_t*, _T&)) [with _C = mavros::std_plugins::SystemStatusPlugin; _T = mavlink::ardupilotmega::msg::HWSTATUS; mavros::plugin::PluginBase::HandlerInfo = std::tuple<unsigned int, const char*, long unsigned int, std::function<void(const mavlink::__mavlink_message*, mavconn::Framing)> >; mavlink::mavlink_message_t = mavlink::__mavlink_message]::<lambda(const mavlink_message_t*, mavconn::Framing)>; <template-parameter-2-2> = void; <template-parameter-2-3> = void; _Res = void; _ArgTypes = {const mavlink::__mavlink_message*, mavconn::Framing}]’, declared using local type ‘mavros::plugin::PluginBase::make_handler(void (_C::*)(const mavlink_message_t*, _T&)) [with _C = mavros::std_plugins::SystemStatusPlugin; _T = mavlink::ardupilotmega::msg::HWSTATUS; mavros::plugin::PluginBase::HandlerInfo = std::tuple<unsigned int, const char*, long unsigned int, std::function<void(const mavlink::__mavlink_message*, mavconn::Framing)> >; mavlink::mavlink_message_t = mavlink::__mavlink_message]::<lambda(const mavlink_message_t*, mavconn::Framing)>’, is used but never defined [-fpermissive]
/usr/include/c++/7/bits/std_function.h:685:7: error: ‘std::function<_Res(_ArgTypes ...)>::function(_Functor) [with _Functor = mavros::plugin::PluginBase::make_handler(void (_C::*)(const mavlink_message_t*, _T&)) [with _C = mavros::std_plugins::SystemStatusPlugin; _T = mavlink::common::msg::AUTOPILOT_VERSION; mavros::plugin::PluginBase::HandlerInfo = std::tuple<unsigned int, const char*, long unsigned int, std::function<void(const mavlink::__mavlink_message*, mavconn::Framing)> >; mavlink::mavlink_message_t = mavlink::__mavlink_message]::<lambda(const mavlink_message_t*, mavconn::Framing)>; <template-parameter-2-2> = void; <template-parameter-2-3> = void; _Res = void; _ArgTypes = {const mavlink::__mavlink_message*, mavconn::Framing}]’, declared using local type ‘mavros::plugin::PluginBase::make_handler(void (_C::*)(const mavlink_message_t*, _T&)) [with _C = mavros::std_plugins::SystemStatusPlugin; _T = mavlink::common::msg::AUTOPILOT_VERSION; mavros::plugin::PluginBase::HandlerInfo = std::tuple<unsigned int, const char*, long unsigned int, std::function<void(const mavlink::__mavlink_message*, mavconn::Framing)> >; mavlink::mavlink_message_t = mavlink::__mavlink_message]::<lambda(const mavlink_message_t*, mavconn::Framing)>’, is used but never defined [-fpermissive]
/usr/include/c++/7/bits/std_function.h:685:7: error: ‘std::function<_Res(_ArgTypes ...)>::function(_Functor) [with _Functor = mavros::plugin::PluginBase::make_handler(void (_C::*)(const mavlink_message_t*, _T&)) [with _C = mavros::std_plugins::SystemStatusPlugin; _T = mavlink::common::msg::EXTENDED_SYS_STATE; mavros::plugin::PluginBase::HandlerInfo = std::tuple<unsigned int, const char*, long unsigned int, std::function<void(const mavlink::__mavlink_message*, mavconn::Framing)> >; mavlink::mavlink_message_t = mavlink::__mavlink_message]::<lambda(const mavlink_message_t*, mavconn::Framing)>; <template-parameter-2-2> = void; <template-parameter-2-3> = void; _Res = void; _ArgTypes = {const mavlink::__mavlink_message*, mavconn::Framing}]’, declared using local type ‘mavros::plugin::PluginBase::make_handler(void (_C::*)(const mavlink_message_t*, _T&)) [with _C = mavros::std_plugins::SystemStatusPlugin; _T = mavlink::common::msg::EXTENDED_SYS_STATE; mavros::plugin::PluginBase::HandlerInfo = std::tuple<unsigned int, const char*, long unsigned int, std::function<void(const mavlink::__mavlink_message*, mavconn::Framing)> >; mavlink::mavlink_message_t = mavlink::__mavlink_message]::<lambda(const mavlink_message_t*, mavconn::Framing)>’, is used but never defined [-fpermissive]
/usr/include/c++/7/bits/std_function.h:685:7: error: ‘std::function<_Res(_ArgTypes ...)>::function(_Functor) [with _Functor = mavros::plugin::PluginBase::make_handler(void (_C::*)(const mavlink_message_t*, _T&)) [with _C = mavros::std_plugins::SystemStatusPlugin; _T = mavlink::common::msg::BATTERY_STATUS; mavros::plugin::PluginBase::HandlerInfo = std::tuple<unsigned int, const char*, long unsigned int, std::function<void(const mavlink::__mavlink_message*, mavconn::Framing)> >; mavlink::mavlink_message_t = mavlink::__mavlink_message]::<lambda(const mavlink_message_t*, mavconn::Framing)>; <template-parameter-2-2> = void; <template-parameter-2-3> = void; _Res = void; _ArgTypes = {const mavlink::__mavlink_message*, mavconn::Framing}]’, declared using local type ‘mavros::plugin::PluginBase::make_handler(void (_C::*)(const mavlink_message_t*, _T&)) [with _C = mavros::std_plugins::SystemStatusPlugin; _T = mavlink::common::msg::BATTERY_STATUS; mavros::plugin::PluginBase::HandlerInfo = std::tuple<unsigned int, const char*, long unsigned int, std::function<void(const mavlink::__mavlink_message*, mavconn::Framing)> >; mavlink::mavlink_message_t = mavlink::__mavlink_message]::<lambda(const mavlink_message_t*, mavconn::Framing)>’, is used but never defined [-fpermissive]
/usr/include/c++/7/bits/std_function.h:685:7: error: ‘std::function<_Res(_ArgTypes ...)>::function(_Functor) [with _Functor = mavros::plugin::PluginBase::make_handler(void (_C::*)(const mavlink_message_t*, _T&)) [with _C = mavros::std_plugins::SystemStatusPlugin; _T = mavlink::common::msg::ESTIMATOR_STATUS; mavros::plugin::PluginBase::HandlerInfo = std::tuple<unsigned int, const char*, long unsigned int, std::function<void(const mavlink::__mavlink_message*, mavconn::Framing)> >; mavlink::mavlink_message_t = mavlink::__mavlink_message]::<lambda(const mavlink_message_t*, mavconn::Framing)>; <template-parameter-2-2> = void; <template-parameter-2-3> = void; _Res = void; _ArgTypes = {const mavlink::__mavlink_message*, mavconn::Framing}]’, declared using local type ‘mavros::plugin::PluginBase::make_handler(void (_C::*)(const mavlink_message_t*, _T&)) [with _C = mavros::std_plugins::SystemStatusPlugin; _T = mavlink::common::msg::ESTIMATOR_STATUS; mavros::plugin::PluginBase::HandlerInfo = std::tuple<unsigned int, const char*, long unsigned int, std::function<void(const mavlink::__mavlink_message*, mavconn::Framing)> >; mavlink::mavlink_message_t = mavlink::__mavlink_message]::<lambda(const mavlink_message_t*, mavconn::Framing)>’, is used but never defined [-fpermissive]
```

**Comment by amilcarlucas** [comment]
Thanks @vooon

**Review by vooon — APPROVED** [review]
LGTM, Thanks!

**Comment by amilcarlucas** [comment]
No clue why CI is complaining on this one.

**Comment by amilcarlucas** [comment]
OK, CI fixed :)

**Pull request merged**
