### PR TITLE
update trajectory

### PR DESCRIPTION
**Pull request by mrivi**
This PR updates the mavlink TRAJECTORY message to be compatible with the recently merged
mavlink/mavlink#915

### CODE REVIEW

**Comment by mhkabir** [comment]
@vooon Can you have a look at the CI failure?

**Comment by mhkabir** [comment]
OK, looks like we need a new mavlink release.

**Comment by TSC21** [comment]
I don't think it is a good idea to merge this type of PR while we don't have the proper mavlink release. This breaks master and obliges other developers to manually update other releases.

**Comment by vooon** [comment]
I merged it *after* release of mavlink and travis ci rebuild.

**Pull request merged**
