### PR TITLE
Issue #1174 Added dependency for mavros_msgs and mavros

### PR DESCRIPTION
**Pull request by acwatkins**

### CODE REVIEW

**Comment by vooon** [comment]
That should be already done by [mavros/package.xml L53](https://github.com/mavlink/mavros/blob/master/mavros/package.xml#L53).
Cross-package dependency in cmake is bad idea.

**Comment by acwatkins** [comment]
I normally do this, for projects that generate messages:
```
add_dependencies(your_program ${catkin_EXPORTED_TARGETS})
```
I believe the above command makes it wait for everything, not just what is used by that section. It seems the above is more accepted though.

http://docs.ros.org/jade/api/catkin/html/howto/format2/cpp_msg_dependencies.html

Some discussion on the topic:
https://answers.ros.org/question/52744/how-to-specify-dependencies-with-foo_msgs-catkin-packages/

**Comment by vooon** [comment]
But mavros uses format 2, so http://docs.ros.org/kinetic/api/catkin/html/howto/format2/cpp_msg_dependencies.html

Can you do that for mavros lib and extras?

**Comment by vooon** [comment]
I will do it myself.

**Pull request merged**
