### PR TITLE
Switched from mavlink VICON_POSITION_ESTIMATE to ATT_POS_MOCAP.

### LINKED ISSUE #228: Update mocap plugin to use new message ATT_POS_MOCAP

### PR DESCRIPTION
**Pull request by tonybaltovski**
This should close #228.

### CODE REVIEW

**Comment by mhkabir** [comment]
Thanks!

With the new message, once I have time, I'll do the changes on the px4 side
to finish off the  mocap interface.

P.S - Travis is broken, can you please check.

**Comment by vooon** [comment]
That message don't exist in mavlink 2014.12.12. I stopped releasing for hydro since i splitted hydro-devel.

**Comment by vooon** [comment]
#232

**Comment by vooon** [comment]
I think jenkins build that without a problem (just done with actuator_control).

**Pull request merged**
