### PR TITLE
local_position: add an aditional topic for velocity on the local frame

### PR DESCRIPTION
**Pull request by TSC21**
Fixes https://github.com/mavlink/mavros/issues/1159. We now have a `local_position/velocity_body`, `local_position/velocity_local` and `local_position/velocity_body_cov` (since only odometry messages contain covariance information, and the velocity on these is in the body frame).

@jkflying can you give a try to this? Thanks.

### CODE REVIEW

**Comment by jkflying** [comment]
On this version I get a continuous stream of the following printed warnings, I don't see them on master:

```
Error:   TF_DENORMALIZED_QUATERNION: Ignoring transform for child_frame_id "fcu" from authority "unknown_publisher" because of an invalid quaternion in the transform (0.000000 0.000000 0.000000 0.000000)
         at line 257 in /tmp/binarydeb/ros-kinetic-tf2-0.5.20/src/buffer_core.cpp
[ERROR] [1548258028.028077195, 11.976000000]: Ignoring transform for child_frame_id "fcu" from authority "unknown_publisher" because of an invalid quaternion in the transform (0.000000 0.000000 0.000000 0.000000)
Error:   TF_DENORMALIZED_QUATERNION: Ignoring transform for child_frame_id "fcu" from authority "unknown_publisher" because of an invalid quaternion in the transform (0.000000 0.000000 0.000000 0.000000)
         at line 257 in /tmp/binarydeb/ros-kinetic-tf2-0.5.20/src/buffer_core.cpp
[ERROR] [1548258028.061005889, 12.012000000]: Ignoring transform for child_frame_id "fcu" from authority "unknown_publisher" because of an invalid quaternion in the transform (0.000000 0.000000 0.000000 0.000000)
[ERROR] [1548258028.061048745, 12.012000000]: Ignoring transform for child_frame_id "fcu" from authority "unknown_publisher" because of an invalid quaternion in the transform (0.000000 0.000000 0.000000 0.000000)

```

**Comment by jkflying** [comment]
@vooon Do you have any rough timeline for the release of 0.29.0? I need to update PX4/Avoidance (https://github.com/PX4/avoidance/pull/197), and I'd prefer to point at a real release rather than a random hash.

**Comment by okalachev** [comment]
@TSC21, why rename `velocity` to `velocity_local`? This has broken everything for us.

Aren't we concerned about backwards compatibility in this project?

**Comment by TSC21** [comment]
> @TSC21, why rename `velocity` to `velocity_local`? This has broken everything for us.
> 
> Aren't we concerned about backwards compatibility in this project?

@okalachev actually your PR initially broke the compatibility for the Avoidance team projects. The only way was to provide both velocity in local and body frame. Renaming it to velocity_local is the normal procedure so to make sure we keep the body and the local velocities properly identified.

**Comment by okalachev** [comment]
I believe back then we reverted back what was breaking the compatibility.

Why not to use `velocity` for local frame (as it used to be) and `velocity_body` for body frame?

**Comment by TSC21** [comment]
We try to keep the backward compatibility the max possible but there are maintenance decisions that need to be taken into account. Your change on the local_position plugin for example took repercussions on other projects and that had to be fixed as well. We always try yo keep the balance between the required changes and the repercussions they take.

**Comment by TSC21** [comment]
> I believe back then we reverted back what was breaking the compatibility.
> 
> Why not to use `velocity` for local frame (as it used to be) and `velocity_body` for body frame?

No that was not the case. `velocity` was publishing body velocities, according to @jkflying and their team. So that had to be reverted.

**Comment by jkflying** [comment]
@okalachev this was changed in your own PR, here: https://github.com/mavlink/mavros/pull/1142

We had to add a new `velocity_local` to get the old values back.

**Comment by okalachev** [comment]
Isn't the new `velocity_local` the same as the old `velocity`?

**Pull request merged**
