### PR TITLE
PID controller for tests

### PR DESCRIPTION
**Pull request by TSC21**
This implements a PID controller so it can be used on velocity control when sending velocity setpoints to the FCU when issuing a offboard control test. Now the velocity is much more smoother and doesn't overshoot cause it's effort is firstly computed on mavros side before sending to the FCU.
Also added usage to `test_setup`, previously named `test_type`.

### CODE REVIEW

**Comment by vooon** [comment]
There several issues with test_mavros packages:

1. Bad names for libraries. Just do `catkin config --install` and after build look inside install/lib directory.
2. Why different library for PID?
3. Why PID instances from PIDControler is outside from class?

In my opinion all that stuff may be written more easy...

**Comment by TSC21** [comment]
> Bad names for libraries. Just do catkin config --install and after build look inside install/lib directory.

OK I'll review this.

> Why different library for PID?
Why PID instances from PIDControler is outside from class?

Well those are not issues as you say. A different lib for the controller cause it's a util and I'm expecting to move this to mavros utils instead of this just existing for test uses. The PID instances it's because I was having problems with the library links on those. If I put them inside the class it gives me a library problem, saying it's not declared, so this was the only solution I found.

**Comment by TSC21** [comment]
@vooon after configuring install space and build it, I can't find any lib related to `test_mavros`. Can you point out the reason?

**Comment by TSC21** [comment]
Update: I removed pid_controller as a lib, done
```
## Declare a cpp library
add_library(
  sitl_test
  sitl_test/lib/sitl_test.cpp
  sitl_test/lib/pid_controller.cpp
)

## Declare a cpp executable
add_executable(
  sitl_test_node
  sitl_test/sitl_test_node.cpp
)

## Add cmake target dependencies of the executable/library
## as an example, message headers may need to be generated before nodes
add_dependencies(
  sitl_test_node
  sitl_test
)

## Specify libraries to link a library or executable target against
target_link_libraries(
  sitl_test
  ${Boost_LIBRARIES}
  ${catkin_LIBRARIES}
)

target_link_libraries(
  sitl_test_node
  sitl_test
)
```
and moved the variables inside the class as:
```c++
	// Control toolbox PID controllers
	static control_toolbox::Pid pid_linvel_x;
	static control_toolbox::Pid pid_linvel_y;
	static control_toolbox::Pid pid_linvel_z;
	static control_toolbox::Pid pid_yaw_rate;

	// PID values
	static std::array<double, 3> linvel_pid;
	static std::array<double, 3> yawrate_pid;

	// Min/max bounds for the integral windup
	static double yawrate_imax;
	static double yawrate_imin;
	static double linvel_imax;
	static double linvel_imin;
```
But then I'm getting these errors when building:
```bash
[100%] Building CXX object CMakeFiles/sitl_test_node.dir/sitl_test/sitl_test_node.cpp.o
Linking CXX executable /home/nuno/AIMAV_Project/devel/lib/test_mavros/sitl_test_node
/home/nuno/AIMAV_Project/devel/lib/libsitl_test.so: undefined reference to `pidcontroller::PIDController::linvel_imin'
/home/nuno/AIMAV_Project/devel/lib/libsitl_test.so: undefined reference to `pidcontroller::PIDController::pid_linvel_x'
/home/nuno/AIMAV_Project/devel/lib/libsitl_test.so: undefined reference to `pidcontroller::PIDController::linvel_pid'
/home/nuno/AIMAV_Project/devel/lib/libsitl_test.so: undefined reference to `pidcontroller::PIDController::pid_linvel_z'
/home/nuno/AIMAV_Project/devel/lib/libsitl_test.so: undefined reference to `pidcontroller::PIDController::yawrate_pid'
/home/nuno/AIMAV_Project/devel/lib/libsitl_test.so: undefined reference to `pidcontroller::PIDController::linvel_imax'
/home/nuno/AIMAV_Project/devel/lib/libsitl_test.so: undefined reference to `pidcontroller::PIDController::yawrate_imin'
/home/nuno/AIMAV_Project/devel/lib/libsitl_test.so: undefined reference to `pidcontroller::PIDController::yawrate_imax'
/home/nuno/AIMAV_Project/devel/lib/libsitl_test.so: undefined reference to `pidcontroller::PIDController::pid_yaw_rate'
/home/nuno/AIMAV_Project/devel/lib/libsitl_test.so: undefined reference to `pidcontroller::PIDController::pid_linvel_y'
collect2: error: ld returned 1 exit status
make[2]: *** [/home/nuno/AIMAV_Project/devel/lib/test_mavros/sitl_test_node] Error 1
make[1]: *** [CMakeFiles/sitl_test_node.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by TSC21** [comment]
I got a workaround by instantiating a object of class `PIDController` and used it on `offboard_controller.h`. Also removed `pid_controller` as a lib for now as it's not really needed.

**Pull request merged**
